# Clean Educator Bank 1 Advanced Math explanations (batch B).
# Transcribed from PDF Rationale bands; MC incorrect choices expanded separately.
# Format-only scan of other Educator AM MC explanations found no remaining
# combined "Choices A, B, and C are incorrect" forms to include.

EXPL = {
    "a9084ca4": (
        "Choice D is correct. The y-intercept of a graph in the xy-plane is the point where x = 0. "
        "For the given function f, the y-intercept of the graph of y = f(x) in the xy-plane can be found by "
        "substituting 0 for x in the equation y = 9,000(0.66)^x, which gives y = 9,000(0.66)^0. This is "
        "equivalent to y = 9,000(1), or y = 9,000. Therefore, the y-intercept of the graph of y = f(x) is "
        "(0, 9,000). It's given that the function f models the number of advertisements a company sent to "
        "its clients each year. Therefore, f(x) represents the estimated number of advertisements the "
        "company sent to its clients each year. It's also given that x represents the number of years since "
        "1997. Therefore, x = 0 represents 0 years since 1997, or 1997. Thus, the best interpretation of the "
        "y-intercept of the graph of y = f(x) is that the estimated number of advertisements the company "
        "sent to its clients in 1997 was 9,000.\n"
        "\n"
        "Choice A is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice B is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice C is incorrect and may result from conceptual or calculation errors."
    ),
    "358f18bc": (
        "The correct answer is 1,728. The given function can be rewritten in the form "
        "f(x) = a(x - h)^2 + k, where a is a positive constant and the minimum value, k, of the function "
        "occurs when the value of x is h. By completing the square, f(x) = x^2 - 48x + 2,304 can be written "
        "as f(x) = x^2 - 48x + (48/2)^2 + 2,304 - (48/2)^2, or f(x) = (x - 24)^2 + 1,728. This equation is "
        "in the form f(x) = a(x - h)^2 + k, where a = 1, h = 24, and k = 1,728. Therefore, the minimum "
        "value of the given function is 1,728."
    ),
    "1d3c5c95": (
        "Choice A is correct. For an exponential function in the form f(x) = a(b)^x, where a and b are "
        "positive constants and b < 1, the initial value of f(x), or the value of f(x) when x = 0, is a and "
        "the value of f(x) decreases by 100(1 - b)% each time x increases by 1. Therefore, the initial "
        "value of the function f(x) = 4,000(0.75)^x, or the value of f(x) when x = 0, is 4,000. Therefore, "
        "the best interpretation of 4,000 in this context is the estimated initial beetle population for "
        "this species and area in 2012.\n"
        "\n"
        "Choice B is incorrect. The estimated beetle population for this species and area 7 years after "
        "2012 is 4,000(0.75)^7, or approximately 534, not 4,000.\n"
        "\n"
        "Choice C is incorrect. The estimated percent decrease in the beetle population for this species "
        "and area each year after 2012 is 100(1 - 0.75), or 25, not 4,000.\n"
        "\n"
        "Choice D is incorrect. The estimated percent decrease in the beetle population for this species "
        "and area every 7 years after 2012 is 100(1 - 0.75^7), or approximately 87, not 4,000."
    ),
    "137cc6fd": (
        "The correct answer is 4/225. An expression of the form the kth root of a, where k is an integer "
        "greater than 1 and a ≥ 0, is equivalent to a^(1/k). Therefore, the given expression, where n > 1, is "
        "equivalent to (70n)^(1/5) * ((70n)^(1/6))^2. Applying properties of exponents, this expression "
        "can be rewritten as (70n)^(1/5) * (70n)^((1/6)*2), or (70n)^(1/5) * (70n)^(1/3), which can be "
        "rewritten as (70n)^(1/5 + 1/3), or (70n)^(8/15). It's given that the expression "
        "(70n)^(1/5) * ((70n)^(1/6))^2 is equivalent to (70n)^(30x), where n > 1. It follows that "
        "(70n)^(8/15) is equivalent to (70n)^(30x). Therefore, 8/15 = 30x. Dividing both sides of this "
        "equation by 30 yields 8/450 = x, or 4/225 = x. Thus, the value of x for which the given "
        "expression is equivalent to (70n)^(30x), where n > 1, is 4/225. Note that 4/225, .0177, .0178, "
        "0.017, and 0.018 are examples of ways to enter a correct answer."
    ),
    "02060533": (
        "Choice A is correct. It's given that the table shows values of x and their corresponding values "
        "of g(x), where g(x) = f(x)/(x + 3). It's also given that f is a linear function. It follows that "
        "an equation that defines f can be written in the form f(x) = mx + b, where m represents the slope "
        "and b represents the y-coordinate of the y-intercept (0, b) of the graph of y = f(x) in the "
        "xy-plane. The slope of the graph of y = f(x) can be found using two points, (x1, y1) and (x2, y2), "
        "that are on the graph of y = f(x), and the formula m = (y2 - y1)/(x2 - x1). Since the table shows "
        "values of x and their corresponding values of g(x), substituting values of x and g(x) in the "
        "equation g(x) = f(x)/(x + 3) can be used to define function f. Using the first pair of values from "
        "the table, x = -27 and g(x) = 3, yields 3 = f(-27)/(-27 + 3), or 3 = f(-27)/(-24). Multiplying each "
        "side of this equation by -24 yields -72 = f(-27), so the point (-27, -72) is on the graph of "
        "y = f(x). Using the second pair of values from the table, x = -9 and g(x) = 0, yields "
        "0 = f(-9)/(-9 + 3), or 0 = f(-9)/(-6). Multiplying each side of this equation by -6 yields "
        "0 = f(-9), so the point (-9, 0) is on the graph of y = f(x). Substituting (-27, -72) and (-9, 0) "
        "for (x1, y1) and (x2, y2), respectively, in the formula m = (y2 - y1)/(x2 - x1) yields "
        "m = (0 - (-72))/(-9 - (-27)), or m = 4. Substituting 4 for m in the equation f(x) = mx + b yields "
        "f(x) = 4x + b. Since 0 = f(-9), substituting -9 for x and 0 for f(x) in the equation f(x) = 4x + b "
        "yields 0 = 4(-9) + b, or 0 = -36 + b. Adding 36 to both sides of this equation yields 36 = b. It "
        "follows that 36 is the y-coordinate of the y-intercept (0, b) of the graph of y = f(x). Therefore, "
        "the y-intercept of the graph of y = f(x) is (0, 36).\n"
        "\n"
        "Choice B is incorrect. 12 is the y-coordinate of the y-intercept of the graph of y = g(x).\n"
        "\n"
        "Choice C is incorrect. 4 is the slope of the graph of y = f(x).\n"
        "\n"
        "Choice D is incorrect. -9 is the x-coordinate of the x-intercept of the graph of y = f(x)."
    ),
    "cc2601cb": (
        "The correct answer is 7. It's given that the x-intercept of the graph shown is (x, 0). The graph "
        "passes through the point (7, 0). Therefore, the value of x is 7."
    ),
    "c3b116d7": (
        "Choice B is correct. The given expression can be factored by first finding two values whose sum "
        "is 20 and whose product is 3(-63), or -189. Those two values are 27 and -7. It follows that the "
        "given expression can be rewritten as 3x^2 + 27x - 7x - 63. Since the first two terms of this "
        "expression have a common factor of 3x and the last two terms of this expression have a common "
        "factor of -7, this expression can be rewritten as 3x(x + 9) - 7(x + 9). Since the two terms of "
        "this expression have a common factor of (x + 9), it can be rewritten as (3x - 7)(x + 9). "
        "Therefore, expression II, 3x - 7, is a factor of 3x^2 + 20x - 63, but expression I, x - 9, is "
        "not a factor of 3x^2 + 20x - 63.\n"
        "\n"
        "Choice A is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice C is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice D is incorrect and may result from conceptual or calculation errors."
    ),
    "b4acba95": (
        "Choice A is correct. The number of solutions of a quadratic equation of the form "
        "ax^2 + bx + c = 0, where a, b, and c are constants, can be determined by the value of the "
        "discriminant, b^2 - 4ac. If the value of the discriminant is positive, then the quadratic "
        "equation has exactly two distinct real solutions. If the value of the discriminant is equal to "
        "zero, then the quadratic equation has exactly one real solution. If the value of the discriminant "
        "is negative, then the quadratic equation has zero real solutions. In the given equation, "
        "x^2 - 12x + 27 = 0, a = 1, b = -12, and c = 27. Substituting these values for a, b, and c in "
        "b^2 - 4ac yields (-12)^2 - 4(1)(27), or 36. Since the value of its discriminant is positive, the "
        "given equation has exactly two distinct real solutions.\n"
        "\n"
        "Choice B is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice C is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice D is incorrect and may result from conceptual or calculation errors."
    ),
    "9654add7": (
        "Choice C is correct. By definition, the y-value when a function intersects the x-axis is 0. It's "
        "given that the graph of the function intersects the x-axis at 0 and a, that x is the unit price, "
        "in dollars, of a product, and that f(x), where y = f(x), is the revenue, in dollars, that a "
        "company receives from the sales of the product. Since the value of a occurs when y = 0, a is the "
        "unit price, in dollars, of the product that will result in a revenue of $0.\n"
        "\n"
        "Choice A is incorrect. The revenue, in dollars, when the unit price of the product is $0 is "
        "represented by f(x), when x = 0.\n"
        "\n"
        "Choice B is incorrect. The unit price, in dollars, of the product that will result in maximum "
        "revenue is represented by the x-coordinate of the maximum of f.\n"
        "\n"
        "Choice D is incorrect. The maximum revenue, in dollars, that the company can make is represented "
        "by the y-coordinate of the maximum of f."
    ),
    "7f2524bf": (
        "Choice A is correct. It's given that the graph shown gives the estimated value y, in dollars, of "
        "a tablet as a function of the number of months since it was purchased, x. The y-intercept of a "
        "graph is the point at which the graph intersects the y-axis, or when x is 0. The graph shown "
        "intersects the y-axis at the point (0, 225). It follows that 0 months after the tablet was "
        "purchased, or when the tablet was purchased, the estimated value of the tablet was 225 dollars. "
        "Therefore, the best interpretation of the y-intercept is that the estimated value of the tablet "
        "was $225 when it was purchased.\n"
        "\n"
        "Choice B is incorrect. The estimated value of the tablet 24 months after it was purchased was "
        "$50, not $225.\n"
        "\n"
        "Choice C is incorrect. The estimated value of the tablet had decreased by $225 - $50, or $175, "
        "not $225, in the 24 months after it was purchased.\n"
        "\n"
        "Choice D is incorrect and may result from conceptual errors."
    ),
    "781c2f6e": (
        "Choice D is correct. A y-intercept of a graph in the xy-plane is a point where the graph "
        "intersects the y-axis, or a point where x = 0. Substituting 0 for x in the equation defining "
        "function f yields f(0) = a(2.2^0 + 2.2^b), or f(0) = a(1 + 2.2^b). So, the y-coordinate of the "
        "y-intercept of the graph is a(1 + 2.2^b), or equivalently, a + a(2.2)^b. It's given that function "
        "g is equivalent to function f, where 0 < a < b. It follows that k = 2.2^b. Since a(2.2)^b can't "
        "be equal to 0, the coefficient a can't be equal to a + a(2.2)^b. Since 0 < a, the constant k, "
        "which is equal to 2.2^b, can't be equal to a + a(2.2)^b. Therefore, function g doesn't display "
        "the y-coordinate of the y-intercept of the graph of y = f(x) in the xy-plane as a constant or "
        "coefficient. It's also given that function h is equivalent to function f, where 0 < a < b. The "
        "equation defining f can be rewritten as f(x) = a(2.2)^x + a(2.2)^b. It follows that m = a(2.2)^b. "
        "Since a(2.2)^b can't be equal to 0, the coefficient a can't be equal to a + a(2.2)^b. Since "
        "0 < a, the constant m, which is equal to a(2.2)^b, can't be equal to a + a(2.2)^b. Therefore, "
        "function h doesn't display the y-coordinate of the y-intercept of the graph of y = f(x) in the "
        "xy-plane as a constant or coefficient. Thus, neither function g nor function h displays the "
        "y-coordinate of the y-intercept of the graph of y = f(x) in the xy-plane as a constant or "
        "coefficient.\n"
        "\n"
        "Choice A is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice B is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice C is incorrect and may result from conceptual or calculation errors."
    ),
    "52b1700c": (
        "Choice C is correct. It's given that the relationship between t and n is exponential. The table "
        "shows that the value of n increases as the value of t increases. Therefore, the relationship "
        "between t and n can be represented by an increasing exponential equation of the form "
        "n = a(1 + b)^t, where a and b are positive constants. The table shows that when t = 0, n = 604. "
        "Substituting 0 for t and 604 for n in the equation n = a(1 + b)^t yields 604 = a(1 + b)^0, which "
        "is equivalent to 604 = a(1), or 604 = a. Substituting 604 for a in the equation n = a(1 + b)^t "
        "yields n = 604(1 + b)^t. The table also shows that when t = 1, n = 606.42. Substituting 1 for t "
        "and 606.42 for n in the equation n = 604(1 + b)^t yields 606.42 = 604(1 + b)^1, or "
        "606.42 = 604(1 + b). Dividing both sides of this equation by 604 yields approximately "
        "1.004 = 1 + b. Subtracting 1 from both sides of this equation yields that the value of b is "
        "approximately 0.004. Substituting 0.004 for b in the equation n = 604(1 + b)^t yields "
        "n = 604(1 + 0.004)^t. Therefore, of the choices, choice C best represents the relationship "
        "between t and n.\n"
        "\n"
        "Choice A is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice B is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice D is incorrect and may result from conceptual or calculation errors."
    ),
    "02add2d2": (
        "Choice B is correct. It's given that in January 2018, there were 1,300 customers subscribed to a "
        "company's newsletter and for the next 24 months after January 2018, the total number of customers "
        "subscribed to the newsletter each month was 7% greater than the total number subscribed the "
        "previous month. It follows that this situation can be represented by the equation "
        "c = a(1 + r/100)^m, where c is the total number of customers subscribed to the company's "
        "newsletter m months after January 2018, a is the number of customers subscribed to the newsletter "
        "in January 2018, and the total number of customers subscribed to the newsletter each month was "
        "r% greater than the total number subscribed the previous month. Substituting 1,300 for a and 7 "
        "for r in this equation yields c = 1,300(1 + 7/100)^m, or c = 1,300(1.07)^m.\n"
        "\n"
        "Choice A is incorrect. This equation represents a situation where the total number of customers "
        "subscribed each month was 93% less, not 7% greater, than the total number subscribed the previous "
        "month.\n"
        "\n"
        "Choice C is incorrect. This equation represents a situation where the total number of customers "
        "subscribed each month was 70%, not 7%, greater than the total number subscribed the previous "
        "month.\n"
        "\n"
        "Choice D is incorrect. This equation represents a situation where the total number of customers "
        "subscribed each month was 600%, not 7%, greater than the total number subscribed the previous "
        "month."
    ),
    "42c71eb5": (
        "Choice A is correct. The given expression can be rewritten as "
        "(2x + 5)^2 + (-1)(x - 2) + 2(x + 3). Applying the distributive property, the expression "
        "(-1)(x - 2) + 2(x + 3) can be rewritten as -1(x) + (-1)(-2) + 2(x) + 2(3), or -x + 2 + 2x + 6. "
        "Adding like terms yields x + 8. Substituting x + 8 for (-1)(x - 2) + 2(x + 3) in the given "
        "expression yields (2x + 5)^2 + x + 8. By the rules of exponents, the expression (2x + 5)^2 is "
        "equivalent to (2x + 5)(2x + 5). Applying the distributive property, this expression can be "
        "rewritten as 2x(2x) + 2x(5) + 5(2x) + 5(5), or 4x^2 + 10x + 10x + 25. Adding like terms gives "
        "4x^2 + 20x + 25. Substituting 4x^2 + 20x + 25 for (2x + 5)^2 in the rewritten expression yields "
        "4x^2 + 20x + 25 + x + 8, and adding like terms yields 4x^2 + 21x + 33.\n"
        "\n"
        "Choice B is incorrect and may result from rewriting the expression -(x - 2) as -x - 2, instead of "
        "-x + 2.\n"
        "\n"
        "Choice C is incorrect. It may result from rewriting the expression (2x + 5)^2 as 4x^2 + 25, "
        "instead of as 4x^2 + 20x + 25. It may also result from rewriting the expression -(x - 2) as "
        "-x - 2, instead of -x + 2.\n"
        "\n"
        "Choice D is incorrect and may result from rewriting the expression (2x + 5)^2 as 4x^2 + 25, "
        "instead of as 4x^2 + 20x + 25."
    ),
}
