# Rebuilt from SAT Educator Bank 1 Advanced Math 1.pdf Rationale sections (batch A).
# Format: correct block, blank line, each incorrect Choice as its own paragraph.

EXPL = {
    "371cbf6b": (
        "Choice C is correct. If the equation is true for all x, then the expressions on both sides of the equation will be equivalent. "
        "Multiplying the polynomials on the left-hand side of the equation gives 5ax^3 - abx^2 + 4ax + 15x^2 - 3bx + 12. "
        "On the right-hand side of the equation, the only x^2-term is -9x^2. "
        "Since the expressions on both sides of the equation are equivalent, it follows that -abx^2 + 15x^2 = -9x^2, "
        "which can be rewritten as (-ab + 15)x^2 = -9x^2. Therefore, -ab + 15 = -9, which gives ab = 24.\n"
        "\n"
        "Choice A is incorrect. If ab = 18, then the coefficient of x^2 on the left-hand side of the equation would be "
        "-18 + 15 = -3, which doesn't equal the coefficient of x^2, -9, on the right-hand side.\n"
        "\n"
        "Choice B is incorrect. If ab = 20, then the coefficient of x^2 on the left-hand side of the equation would be "
        "-20 + 15 = -5, which doesn't equal the coefficient of x^2, -9, on the right-hand side.\n"
        "\n"
        "Choice D is incorrect. If ab = 40, then the coefficient of x^2 on the left-hand side of the equation would be "
        "-40 + 15 = -25, which doesn't equal the coefficient of x^2, -9, on the right-hand side."
    ),
    "40491607": (
        "The correct answer is 48. It's given that in the xy-plane, when the graph of the function f, where y = f(x), "
        "is shifted up 6 units, the resulting graph is defined by the function g. Therefore, function g can be defined "
        "by the equation g(x) = f(x) + 6. It's given that f(x) = (x - 1)(x + 3)(x - 2). Substituting (x - 1)(x + 3)(x - 2) "
        "for f(x) in the equation g(x) = f(x) + 6 yields g(x) = (x - 1)(x + 3)(x - 2) + 6. For the point (4, b), the value "
        "of x is 4. Substituting 4 for x in the equation g(x) = (x - 1)(x + 3)(x - 2) + 6 yields "
        "g(4) = (4 - 1)(4 + 3)(4 - 2) + 6, or g(4) = 48. It follows that the graph of y = g(x) crosses through the point "
        "(4, 48). Therefore, the value of b is 48."
    ),
    "301faf80": (
        "The correct answer is 14. Let x represent the first integer and y represent the second integer. If the first "
        "integer is 5 greater than twice the second integer, then x = 2y + 5. It's given that the product of the two "
        "integers is 462; therefore xy = 462. Substituting 2y + 5 for x in this equation yields (2y + 5)(y) = 462, which "
        "can be written as 2y^2 + 5y = 462. Subtracting 462 from each side of this equation yields 2y^2 + 5y - 462 = 0. "
        "The left-hand side of this equation can be factored by finding two values whose product is 2(-462), or -924, "
        "and whose sum is 5. The two values whose product is -924 and whose sum is 5 are 33 and -28. Thus, the equation "
        "2y^2 + 5y - 462 = 0 can be rewritten as 2y^2 - 28y + 33y - 462 = 0, which is equivalent to "
        "2y(y - 14) + 33(y - 14) = 0, or (2y + 33)(y - 14) = 0. By the zero product property, it follows that "
        "2y + 33 = 0 or y - 14 = 0. Subtracting 33 from both sides of the equation 2y + 33 = 0 yields 2y = -33. Dividing "
        "both sides of this equation by 2 yields y = -33/2. Since y is a positive integer, the value of y isn't -33/2. "
        "Adding 14 to both sides of the equation y - 14 = 0 yields y = 14. Substituting 14 for y in the equation "
        "xy = 462 yields x(14) = 462. Dividing both sides of this equation by 14 yields x = 33. Therefore, the two "
        "integers are 14 and 33, so the smaller of the two integers is 14."
    ),
    "beca03de": (
        "Choice A is correct. It's given that a rectangle has a length that is 15 times its width. It's also given that "
        "the function y = (15w)(w) represents this situation, where y is the area, in square feet, of the rectangle and "
        "y > 0. The area of a rectangle can be calculated by multiplying the rectangle's length by its width. Since the "
        "rectangle has a length that is 15 times its width, it follows that w represents the width of the rectangle, in "
        "feet, and 15w represents the length of the rectangle, in feet. Therefore, the best interpretation of 15w in "
        "this context is that it's the length of the rectangle, in feet.\n"
        "\n"
        "Choice B is incorrect. This is the best interpretation of y, not 15w, in the given function.\n"
        "\n"
        "Choice C is incorrect and may result from conceptual errors.\n"
        "\n"
        "Choice D is incorrect. This is the best interpretation of w, not 15w, in the given function."
    ),
    "f5aa5040": (
        "The correct answer is 81/4. The given linear equation is 2y = c. Dividing both sides of this equation by 2 "
        "yields y = c/2. Substituting c/2 for y in the equation of the parabola yields c/2 = -2x^2 + 9x. Adding 2x^2 "
        "and -9x to both sides of this equation yields 2x^2 - 9x + c/2 = 0. Since it's given that the line and the "
        "parabola intersect at exactly one point, the equation 2x^2 - 9x + c/2 = 0 must have exactly one solution. An "
        "equation of the form Ax^2 + Bx + C = 0, where A, B, and C are constants, has exactly one solution when the "
        "discriminant, B^2 - 4AC, is equal to 0. In the equation 2x^2 - 9x + c/2 = 0, where A = 2, B = -9, and C = c/2, "
        "the discriminant is (-9)^2 - 4(2)(c/2). Setting the discriminant equal to 0 yields (-9)^2 - 4(2)(c/2) = 0, or "
        "81 - 4c = 0. Adding 4c to both sides of this equation yields 81 = 4c. Dividing both sides of this equation by "
        "4 yields c = 81/4. Note that 81/4 and 20.25 are examples of ways to enter a correct answer."
    ),
    "7902bed0": (
        "Choice D is correct. An equation representing the height above ground h, in meters, of a softball t seconds "
        "after it is launched by a machine from ground level can be written in the form h = -a(t - b)^2 + c, where a, "
        "b, and c are positive constants. In this equation, b represents the time, in seconds, at which the softball "
        "reaches its maximum height of c meters above the ground. It's given that this softball reaches a maximum "
        "height of 51.84 meters above the ground at 1.8 seconds; therefore, b = 1.8 and c = 51.84. Substituting 1.8 "
        "for b and 51.84 for c in the equation h = -a(t - b)^2 + c yields h = -a(t - 1.8)^2 + 51.84. It's also given "
        "that this softball hits the ground at 3.6 seconds; therefore, h = 0 when t = 3.6. Substituting 0 for h and "
        "3.6 for t in the equation h = -a(t - 1.8)^2 + 51.84 yields 0 = -a(3.6 - 1.8)^2 + 51.84, which is equivalent "
        "to 0 = -a(1.8)^2 + 51.84, or 0 = -3.24a + 51.84. Adding 3.24a to both sides of this equation yields "
        "3.24a = 51.84. Dividing both sides of this equation by 3.24 yields a = 16. Substituting 16 for a in the "
        "equation h = -a(t - 1.8)^2 + 51.84 yields h = -16(t - 1.8)^2 + 51.84. Therefore, "
        "h = -16(t - 1.8)^2 + 51.84 represents the height above ground h, in meters, of this softball t seconds after "
        "it is launched.\n"
        "\n"
        "Choice A is incorrect. This equation represents a situation where the maximum height is 3.6 meters above the "
        "ground at 0 seconds, not 51.84 meters above the ground at 1.8 seconds.\n"
        "\n"
        "Choice B is incorrect. This equation represents a situation where the maximum height is 51.84 meters above "
        "the ground at 0 seconds, not 1.8 seconds.\n"
        "\n"
        "Choice C is incorrect and may result from conceptual or calculation errors."
    ),
    "f65288e8": (
        "Choice A is correct. The given equation can be rewritten as 1/(x + 5)^2 = 4. Multiplying both sides of this "
        "equation by (x + 5)^2 yields 1 = 4(x + 5)^2. Dividing both sides of this equation by 4 yields "
        "1/4 = (x + 5)^2. Taking the square root of both sides of this equation yields 1/2 = x + 5 or "
        "-1/2 = x + 5. Therefore, a possible value of x + 5 is 1/2.\n"
        "\n"
        "Choice B is incorrect and may result from computational or conceptual errors.\n"
        "\n"
        "Choice C is incorrect and may result from computational or conceptual errors.\n"
        "\n"
        "Choice D is incorrect and may result from computational or conceptual errors."
    ),
    "e53add44": (
        "Choice C is correct. A model for a quantity S that increases by a certain percentage per time period n is an "
        "exponential function in the form S(n) = I(1 + r/100)^n, where I is the initial value at time n = 0 for r% "
        "annual increase. It's given that the annual increase in an employee's salary is 4%, so r = 4. The initial "
        "value can be found by substituting 0 for n in the given function, which yields S(0) = 38,000. Therefore, "
        "I = 38,000. Substituting these values for r and I into the form of the exponential function "
        "S(n) = I(1 + r/100)^n yields S(n) = 38,000(1 + 4/100)^n, or S(n) = 38,000(1.04)^n. Therefore, the value of a "
        "in the given function is 1.04.\n"
        "\n"
        "Choice A is incorrect and may result from incorrectly representing the annual increase in the exponential function.\n"
        "\n"
        "Choice B is incorrect and may result from incorrectly representing the annual increase in the exponential function.\n"
        "\n"
        "Choice D is incorrect and may result from incorrectly representing the annual increase in the exponential function."
    ),
    "b8f13a3a": (
        "The correct answer is 20. It's given that f(x) = -a^x + b. Substituting -a^x + b for f(x) in the equation "
        "y = f(x) - 12 yields y = -a^x + b - 12. It's given that the y-intercept of the graph of y = f(x) - 12 is "
        "(0, -75/7). Substituting 0 for x and -75/7 for y in the equation y = -a^x + b - 12 yields "
        "-75/7 = -a^0 + b - 12, which is equivalent to -75/7 = -1 + b - 12, or -75/7 = b - 13. Adding 13 to both sides "
        "of this equation yields 16/7 = b. It's given that the product of a and b is 320/7, or ab = 320/7. Substituting "
        "16/7 for b in this equation yields (a)(16/7) = 320/7. Dividing both sides of this equation by 16/7 yields "
        "a = 20."
    ),
    "8e1da169": (
        "Choice B is correct. It's given that f(x) = (x - 44)(x - 46), which can be rewritten as "
        "f(x) = x^2 - 90x + 2,024. Since the coefficient of the x^2-term is positive, the graph of y = f(x) in the "
        "xy-plane opens upward and reaches its minimum value at its vertex. For an equation in the form "
        "f(x) = ax^2 + bx + c, where a, b, and c are constants, the x-coordinate of the vertex is -b/(2a). For the "
        "equation f(x) = x^2 - 90x + 2,024, a = 1, b = -90, and c = 2,024. It follows that the x-coordinate of the "
        "vertex is -(-90)/(2(1)), or 45. Therefore, f(x) reaches its minimum when the value of x is 45.\n"
        "\n"
        "Choice A is incorrect. This is one of the x-coordinates of the x-intercepts of the graph of y = f(x) in the "
        "xy-plane.\n"
        "\n"
        "Choice C is incorrect. This is one of the x-coordinates of the x-intercepts of the graph of y = f(x) in the "
        "xy-plane.\n"
        "\n"
        "Choice D is incorrect. This is the y-coordinate of the vertex of the graph of y = f(x) in the xy-plane."
    ),
    "34847f8a": (
        "Choice C is correct. To express the sum of the two rational expressions on the left-hand side of the equation "
        "as the single rational expression on the right-hand side of the equation, the expressions on the left-hand "
        "side must have the same denominator. Multiplying the first expression by (x + 5)/(x + 5) results in "
        "2(x + 5)/((x - 2)(x + 5)), and multiplying the second expression by (x - 2)/(x - 2) results in "
        "3(x - 2)/((x - 2)(x + 5)), so the given equation can be rewritten as "
        "2(x + 5)/((x - 2)(x + 5)) + 3(x - 2)/((x - 2)(x + 5)) = (rx + t)/((x - 2)(x + 5)), or "
        "(2x + 10)/((x - 2)(x + 5)) + (3x - 6)/((x - 2)(x + 5)) = (rx + t)/((x - 2)(x + 5)). Since the two rational "
        "expressions on the left-hand side of the equation have the same denominator as the rational expression on the "
        "right-hand side of the equation, it follows that (2x + 10) + (3x - 6) = rx + t. Combining like terms on the "
        "left-hand side yields 5x + 4 = rx + t, so it follows that r = 5 and t = 4. Therefore, the value of rt is "
        "(5)(4) = 20.\n"
        "\n"
        "Choice A is incorrect and may result from an error when determining the sign of either r or t.\n"
        "\n"
        "Choice B is incorrect and may result from not distributing the 2 and 3 to their respective terms in "
        "2(x + 5)/((x - 2)(x + 5)) + 3(x - 2)/((x - 2)(x + 5)) = (rx + t)/((x - 2)(x + 5)).\n"
        "\n"
        "Choice D is incorrect and may result from a calculation error."
    ),
    "ff8c5844": (
        "Choice D is correct. It's given that function g is exponential. Therefore, an equation defining g can be "
        "written in the form g(x) = a(b)^x, where a and b are constants. The table shows that when x = 0, g(x) = 1. "
        "Substituting 0 for x and 1 for g(x) in the equation g(x) = a(b)^x yields 1 = a(b)^0, which is equivalent to "
        "1 = a. Substituting 1 for a in the equation g(x) = a(b)^x yields g(x) = (b)^x. The table also shows that when "
        "x = 1, g(x) = 1/25. Substituting 1 for x and 1/25 for g(x) in the equation g(x) = (b)^x yields "
        "1/25 = (b)^1, which is equivalent to 1/25 = b. Substituting 1/25 for b in the equation g(x) = (b)^x yields "
        "g(x) = (1/25)^x.\n"
        "\n"
        "Choice A is incorrect. For this function, g(1) is equal to -25, not 1/25.\n"
        "\n"
        "Choice B is incorrect. For this function, g(1) is equal to -1/25, not 1/25.\n"
        "\n"
        "Choice C is incorrect. For this function, g(1) is equal to 25, not 1/25."
    ),
    "f89af023": (
        "Choice A is correct. It's given that the volleyball court is rectangular and has an area of 162 square meters. "
        "The formula for the area of a rectangle is A = ℓ · w, where A is the area, ℓ is the length, and w is the width "
        "of the rectangle. It's also given that the length of the volleyball court is twice the width, thus ℓ = 2w. "
        "Substituting the given value into the formula for the area of a rectangle and using the relationship between "
        "length and width for this rectangle yields 162 = (2w)(w). This equation can be rewritten as 162 = 2w^2. "
        "Dividing both sides of this equation by 2 yields 81 = w^2. Taking the square root of both sides of this "
        "equation yields ±9 = w. Since the width of a rectangle is a positive number, the width of the volleyball "
        "court is 9 meters.\n"
        "\n"
        "Choice B is incorrect because this is the length of the rectangle.\n"
        "\n"
        "Choice C is incorrect because this is the result of using 162 as the perimeter rather than the area.\n"
        "\n"
        "Choice D is incorrect because this is the result of calculating w in the equation 162 = 2w + w instead of "
        "162 = (2w)(w)."
    ),
    "ebed7dc6": (
        "Choice B is correct. It's given that the situation can be modeled by the equation "
        "y = -100x^2 + 1,400x + 7,200, where x represents the increase in ticket price, in dollars, and y represents "
        "the revenue, in dollars, from ticket sales. Since the coefficient of the x^2 term is negative, the graph of "
        "this equation in the xy-plane opens downward and reaches its maximum value at its vertex. If a quadratic "
        "equation in the form y = ax^2 + bx + c, where a, b, and c are constants, is graphed in the xy-plane, the "
        "x-coordinate of the vertex is equal to -b/(2a). For the equation y = -100x^2 + 1,400x + 7,200, a = -100, "
        "b = 1,400, and c = 7,200. It follows that the x-coordinate of the vertex is -1,400/(2(-100)), or 7. Therefore, "
        "if the given equation is graphed in the xy-plane, the maximum of the graph occurs at an x-value of 7.\n"
        "\n"
        "Choice A is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice C is incorrect and may result from conceptual or calculation errors.\n"
        "\n"
        "Choice D is incorrect and may result from conceptual or calculation errors."
    ),
}
